version: '3.8'
services:
  app:
    image: greatcloud13/spring-boot-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://mysql:3306/springdb
      - DATABASE_USERNAME=springuser
      - DATABASE_PASSWORD=p@ss

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: springdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: p@ss
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
