# application-docker.yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/springdb
    username: springuser
    password: p@ss
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update  # create-drop 대신 update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# JWT 설정
app:
  jwt:
    secret: dockerJwtSecretKey123456789012345678901234567890
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

# 로깅
logging:
  level:
    com.example.webapp: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG